config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end

  resources :gists, only: :create

  namespace :admin do
    resources :gists, only: :index
    resources :tests do
      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  PASSING_SCORE_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_next_question

  def accept!(answer_ids)
    increment(:correct_questions) if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def score
    ((correct_questions.to_f / test.questions.count) * 100).to_i
  end

  def question_number
    test.questions.order(:id).ids.index(current_question.id) + 1
  end

  def success?
    score > PASSING_SCORE_PERCENT
  end

  private

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids&.map(&:to_i)&.sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def before_update_next_question
    self.current_question = next_question
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage, only: %i[show update result]

  def show
    @questions_count = @test_passage.test.questions.size
  end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      redirect_to @test_passage
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def passing_result_title_score(test_passage)
    score = test_passage.score
    if test_passage.success?
      "<h2> You passed the Test </h2>
       <lable>Your score: </lable> <span class= 'green'>#{score}%</span>".html_safe
    else
      "<h2> You failed the Test </h2>
       <lable>Your score: </lable> <span class= 'red'>#{score}%</span>".html_safe
    end
  end
end

app/views/test_passages/result.html.haml
%h1
  = t('.header', title: @test_passage.test.title)
%b
  = passing_result_title_score(@test_passage)
%p
  = link_to "Back to Tests page", tests_path

app/views/test_passages/show.html.haml
%h1
  = "Passing the #{@test_passage.test.title} Test"
%p  
  = "Question #{@test_passage.question_number} from #{@questions_count}"
%br

%p
  %b
    = @test_passage.current_question.body

= form_with url: test_passage_path(@test_passage), method: :put do |f|
  = f.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b|
    %p
      = b.check_box id: "answer_ids_#{b.object.id}"
      = b.label
  %p
    = link_to 'Gist Question', gists_path(test_passage_id: @test_passage.id), method: :post
  %p
    = f.submit 'Next'