config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end

  resources :gists, only: :create

  namespace :admin do
    resources :gists, only: :index
    resources :tests do
      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_max_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers
    errors[:base] << 'Too many answers' if question.answers.size > 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  def show; end

  def edit; end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/views/admin/answers/_answer.html.haml
%li
  = answer.body
  = link_to 'Show', admin_answer_path(answer)
  = link_to 'Edit', edit_admin_answer_path(answer)
  = link_to 'Delete', admin_answer_path(answer),
                      method: :delete,
                      data: { confirm: 'Are you sure?' }

app/views/admin/answers/_form.html.haml
= form_with model: [:admin, @question, @answer] do |f|
  %p
    %p
      = f.label :body
    = f.text_area :body, id: :answer_body, rows: 7, cols: 60

  %p
    = f.label :correct
    = f.check_box :correct, id: :answer_correct
  %p
    = f.submit

app/views/admin/answers/edit.html.haml
%h1 Edit Answer
%p
  = @answer.question.body
= render 'form'
= link_to 'Back', admin_question_path(@answer.question)

app/views/admin/answers/new.html.haml
%h1 New Answer
%p
  = @question.body

= render 'form'
= link_to 'Back', admin_question_path(@question)

app/views/admin/answers/show.html.haml
%h1 Question

%p
  = @answer.question.body

%p
  %b Answer:
  = @answer.body

%p
  %b Correct:
  = @answer.correct

= link_to 'Back', admin_question_path(@answer.question)