config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end

  resources :gists, only: :create

  namespace :admin do
    resources :gists, only: :index
    resources :tests do
      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[new create index]
  before_action :find_question, only: %i[show destroy edit update]

  def index; end

  def new; end

  def show; end

  def edit; end

  def create
    @question = @test.questions.build(question_params)

    if @question.save
      redirect_to admin_test_path(@test)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    question.new_record? ? "Create new #{question.test.title} Question" : "Edit #{question.test.title} Question"
  end
end

app/views/admin/questions/_form.html.haml
= form_with model: [test, question], url: url do |f|
  %lable Question
  = f.text_field :body
  = f.submit

app/views/admin/questions/_question.html.haml
%tr
  %td= question.id
  %td= question.body
  %td= link_to 'Show', admin_question_path(question), method: :get
  %td= link_to 'Edit', edit_admin_question_path(question)
  %td= link_to 'Delete', admin_question_path(question), method: :delete, data: {confirm: 'Are you sure you want to delete this question?'}

app/views/admin/questions/_questions.html.haml
%table
  %tr
    %th id
    %th Question body
    %th{colspan: 3} Actions
  %tbody
    = render partial: 'admin/questions/question', collection: questions

app/views/admin/questions/edit.html.haml
%h1= question_header(@question)
= render 'form', test: @question.test, 
                 question: @question, 
                 url: admin_question_path(@question)
%br
= link_to 'Back', admin_test_path(@question.test)

app/views/admin/questions/index.html.haml
%h1=  "Questions for Test: #{@test.title}"
= render 'questions', questions: @questions
%br
= button_to 'new question', new_admin_test_question_path, method: :get
%br
= link_to 'Back', admin_tests_path

app/views/admin/questions/new.html.haml
- question = @test.questions.build
%h1= question_header(question)
= render 'form', test: @test, 
                 question: question, 
                 url: admin_test_questions_path(@test)
%br
= link_to 'Back', admin_test_path(@test)

app/views/admin/questions/show.html.haml
%h1
  = "#{@question.test.title.capitalize} Question"
%p= @question.body

%h2 Answers
= link_to 'new_answer', new_admin_question_answer_path(@question)

%ol
  = render @question.answers

= link_to 'Back', admin_test_path(@question.test)
= link_to 'Edit', edit_admin_question_path